name: tf-gpu
channels:
- defaults
- conda-forge
dependencies:
  - python=3.9
  - cudatoolkit=11.2
  - cudnn=8.1.0
  - music21
  - jupyterlab
  # - huggingface::transformers
  # - datasets
  - pip
  - pip:
    - tensorflow==2.11
    - black
    - flake8
    - mypy
    - transformers
    - datasets
    - sacremoses
    - keras-nlp
# prefix: /home/deglasfl/miniconda3/envs/tf-gpu
