name: New Release

on:
  push:
    tags:
    - "v*.*.*"

jobs:
  update-pyproject:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install Poetry
      uses: abatilo/actions-poetry@v2

    - name: Update pyproject.toml
      run: poetry version ${{ github.ref_name }}

    - name: Commit changes
      uses: EndBug/add-and-commit@v9.1.1
      with:
        default_author: github_actions
        message: Update pyproject.toml
        add: pyproject.toml
        push: false

    - name: Relocate git tag
      run: git tag -f ${{ github.ref_name }}

    - name: Push changes
      run: |
        git push origin HEAD:${{ github.ref_name }} --force
        git push origin HEAD:${{ github.ref_name }} --tag --force

  build:
    needs: update-pyproject
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref_name }}

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install Poetry
      uses: abatilo/actions-poetry@v2

    - name: Build package
      run: poetry build --no-interaction

    - name: Upload package
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist

  publish:
    needs: build
    runs-on: ubuntu-latest
    environment: PyPi token

    steps:
    - name: Download package
      uses: actions/download-artifact@v3
      with:
        name: dist
        path: dist

    - name: Print package
      run: ls -l dist

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download package
      uses: actions/download-artifact@v3
      with:
        name: dist
        path: dist

    - name: Create Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        prerelease: false
        files: |
          dist/*
