name: Update requirements

on:
  push:
    paths:
      - poetry.lock

jobs:
  # Udate requirements.txt
  update-requirements:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
      
      - name: Export requirements.txt
        run: poetry export -f requirements.txt --without-hashes --output requirements.txt

      - name: Export requirements-dev.txt
        run: poetry export -f requirements.txt --without-hashes --with=dev --output requirements-dev.txt

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: ${{ github.actor }}
          author_email: ${{ github.actor }}@users.noreply.github.com
          message: Update requirements
          add: requirements.txt requirements-dev.txt